services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: superSecurePass123
      POSTGRES_DB: contacts_db
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - '8000:8000'
    env_file:
      - .env
    command:
      - uvicorn
      - app.main:app
      - --host
      - '0.0.0.0'
      - --port
      - '8000'

volumes:
  postgres_data:
